In [1]:
# Machine Learning
''' 
   1. Supervised (label data set having both input and output)
   2. Unsupervised (unlabel data set having only inputs)
   3. Reinforcement (pusnishments based on exp. and learn data)
'''

#Supervised Learning
'''
    1. Regression  (numerical targeted variable)
    2. Classification (catogerical targeted variable)

'''
# Regression 
'''
   1. Linear Regression
   2. Support vector Regresssion
   3. Dicision tree Regression
   4. Random forset Regression

'''

'\n   1. Linear Regression\n   2. Support vector Regresssion\n   3. Dicision tree Regression\n   4. Random forset Regression\n\n'

In [2]:
#Linear Regression
import pandas as pd
df = pd.read_csv("experience_vs_salary.csv")
df

   Experience (Years)  Salary ($)
0                   1       30000
1                   2       35000
2                   3       40000
3                   4       45000
4                   5       50000
5                   6       60000
6                   7       65000
7                   8       75000
8                   9       85000
9                  10       95000

In [8]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\mirzas\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in c:\users\mirzas\anaconda3\lib\site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.8.0 in c:\users\mirzas\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\mirzas\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\mirzas\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)

In [4]:
X=df[["Experience (Years)"]]    # Input varaible 
Y=df["Salary ($)"]              # Targetted variable
from sklearn.linear_model import LinearRegression         # Skit learn is a library that provides ML Algorithms or models
model=LinearRegression()        # Select the model
model.fit(X,Y)                  # Fit the model
y_pred=model.predict(X)
print(y_pred)

[25818.18181818 32969.6969697  40121.21212121 47272.72727273
 54424.24242424 61575.75757576 68727.27272727 75878.78787879
 83030.3030303  90181.81818182]

In [ ]:
#Find error now
'''
   1. MAE (Mean Absolute Error)
   2. MSE (Mean Square Error)
   3. RMSE (Root Mean Square Error)
   4. R-2 Score 
---> if R-2 value is near to 1 then the model is good
'''

In [7]:
from sklearn.metrics import mean_squared_error,r2_score
mse=mean_squared_error(Y,y_pred)
r2=r2_score(Y,y_pred)
print("Mean Squared Error : ", mse)
print("R2 Score : " , r2)

Mean Squared Error :  9060606.060606051
R2 Score :  0.9789777121563664

In [8]:
#coorelations
# it is a statistical measure to find the relationship between the two cloumns (input and output)
'''
    1. value > 0.5 (Strong +)
    2. value between 0 to 0.5 (Weak +)
    3. value between 0 to -0.5 (Weak -)
    4. value > -0.5 (Strong +)

----> we just only consider Strong Positive and Strong Negative     
   
'''
# Multi Linear Regresssion 
'''
----> Take multiple inputs and predict one output

'''

In [18]:
import numpy as np
import pandas as pd
df=pd.read_csv("Cars_4vars.csv")
df

     HP        MPG  VOL          SP         WT
0    49  53.700681   89  104.185353  28.762059
1    55  50.013401   92  105.461264  30.466833
2    55  50.013401   92  105.461264  30.193597
3    70  45.696322   92  113.461264  30.632114
4    53  50.504232   92  104.461264  29.889149
..  ...        ...  ...         ...        ...
76  322  36.900000   50  169.598513  16.132947
77  238  19.197888  115  150.576579  37.923113
78  263  34.000000   50  151.598513  15.769625
79  295  19.833733  119  167.944460  39.423099
80  236  12.101263  107  139.840817  34.948615

[81 rows x 5 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   HP      81 non-null     int64
 1   MPG     81 non-null     float64
 2   VOL     81 non-null     int64
 3   SP      81 non-null     float64
 4   WT      81 non-null     float64
dtypes: float64(3), int64(2)
memory usage: 3.3 KB

In [11]:
df.isnull().sum()

HP     0
MPG    0
VOL    0
SP     0
WT     0
dtype: int64

In [21]:
'''
MPG is targetted variable 
first arrange in order 
MPG ---> Hp ---> -0.725 (Strong Negative)
MPG ---> Hp ,Sp ---> -0.68 (Strong Negative)
MPG ---> Hp ,Sp , Vol  ---> -0.529 
MPG ---> Hp , Sp , Vol , WT ---> -0.526

'''

df.corr() # to know the corealtions

           HP       MPG       VOL        SP        WT
HP   1.000000 -0.725038  0.077459  0.973848  0.076513
MPG -0.725038  1.000000 -0.529057 -0.687125 -0.526759
VOL  0.077459 -0.529057  1.000000  0.102170  0.999203
SP   0.973848 -0.687125  0.102170  1.000000  0.102439
WT   0.076513 -0.526759  0.999203  0.102439  1.000000

In [28]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error , r2_score

In [34]:
#Model 1 : using only HP highest corelation with MPG
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error , r2_score
X=df[["HP"]]
Y_multi=df["MPG"]
model1=LinearRegression()
model1.fit(X,Y_multi)
y_pred1=model1.predict(X)
r2_model1=r2_score(Y_multi,y_pred1)
mse_model1=mean_squared_error(Y_multi,y_pred1)
rmse_model1=np.sqrt(mse)
print("r2_score :",r2_model1)
print("mse : ",mse_model1)
print("rmse : ", rmse_model1)

r2_score : 0.5256806086282022
mse :  39.06203258359856
rmse :  6.249962606576023

In [36]:
#Model 2 :  using Hp,SP 2nd higest corelation with MPG
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error , r2_score
X=df[["HP","SP"]]
Y_multi=df["MPG"]
model2=LinearRegression()
model2.fit(X,Y_multi)
y_pred2=model2.predict(X)
r2_model2 =r2_score(Y_multi,y_pred2)
mse_model2=mean_squared_error(Y_multi,y_pred2)
rmse_model2=np.sqrt(mse)
print("r2_score :",r2_model2)
print("mse :",mse_model2)
print("rmse : ", rmse_model2)

r2_score : 0.532639171285165
mse : 38.488968091221025
rmse :  6.249962606576023

In [41]:
#Model 3 : Using Hp,SP,VOl 3rd Higest corelation with MPG
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error , r2_score
X=df[["HP","SP","VOL"]]
Y_multi=df["MPG"]
model3=LinearRegression()
model3.fit(X,Y_multi)
y_pred3=model3.predict(X)
r2_model3=r2_score(Y_multi,y_pred3)
mse_model3=mean_squared_error(Y_multi,y_pred3)
rmse_model3=np.sqrt(mse)
print("r2_score :",r2_model3)
print("mse :",mse_model3)
print("rmse : ", rmse_model3)

r2_score : 0.770368341321302
mse : 18.91105338871122
rmse :  6.249962606576023

In [43]:
#Model 4 : Using Hp,SP,VOl,WT 4th Higest corelation with MPG
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error , r2_score
X=df[["HP","SP","VOL","WT"]]
Y_multi=df["MPG"]
model4=LinearRegression()
model4.fit(X,Y_multi)
y_pred4=model4.predict(X)
r2_model4=r2_score(Y_multi,y_pred4)
mse_model4=mean_squared_error(Y_multi,y_pred4)
rmse_model4=np.sqrt(mse)
print("r2_score :",r2_model3)
print("mse :",mse_model3)
print("rmse : ", rmse_model3)

r2_score : 0.770368341321302
mse : 18.91105338871122
rmse :  6.249962606576023

In [46]:
#Multi Colinearity
'''
  --> when we have high corelation btw two indipendent variable 
  ---> it affects model performace
  ---> To avoid we need to find VIF (varaince Inflation Factor)

  VIF = 1 / (1 - r2_score)
  
'''
print()

In [53]:
# VIF of Hp and Sp 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error , r2_score
X_sp=df[["SP"]]
Y_hp=df["HP"]
model_sp_hp=LinearRegression()
model_sp_hp.fit(X_sp,Y_hp)
y_hp_pred=model_sp_hp.predict(X_sp)
r2_sp_hp=r2_score(Y_hp,y_hp_pred)
VIF_sp_hp=1/(1-r2_sp_hp)
print(VIF_sp_hp)

19.372361711379014

In [54]:
# VIF of Sp and Vol
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error , r2_score
X_sp=df[["SP"]]
Y_vol=df["VOL"]
model_sp_vol=LinearRegression()
model_sp_vol.fit(X_sp,Y_vol)
y_vol_pred=model_sp_vol.predict(X_sp)
r2_sp_vol=r2_score(Y_vol,y_vol_pred)
VIF_sp_vol=1/(1-r2_sp_vol)
print(VIF_sp_vol)

1.0105488269989298

In [55]:
# VIF of Vol and WT
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error , r2_score
X_wt=df[["WT"]]
Y_vol=df["VOL"]
model_wt_vol=LinearRegression()
model_wt_vol.fit(X_wt,Y_vol)
y_vol_pred=model_wt_vol.predict(X_wt)
r2_wt_vol=r2_score(Y_vol,y_vol_pred)
VIF_wt_vol=1/(1-r2_wt_vol)
print(VIF_wt_vol)

627.6657966335137

In [56]:
# VIF of Vol and hp
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error , r2_score
X_hp=df[["HP"]]
Y_vol=df["VOL"]
model_hp_vol=LinearRegression()
model_hp_vol.fit(X_hp,Y_vol)
y_vol_pred=model_hp_vol.predict(X_hp)
r2_hp_vol=r2_score(Y_vol,y_vol_pred)
VIF_hp_vol=1/(1-r2_hp_vol)
print(VIF_hp_vol)

1.0060361869916132

In [58]:
#R2 Score betweeen HP AND VOL
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error , r2_score
X=df[["HP","VOL"]]
Y_multi=df["MPG"]
Fmodel=LinearRegression()
Fmodel.fit(X,Y_multi)
y_predF=Fmodel.predict(X)
r2_Fmodel=r2_score(Y_multi,y_predF)
print(r2_Fmodel)

0.7506606277376423

In [ ]:
'''
So using HP AND VOL we can predict good score
'''